# Generated by Django 4.1.4 on 2023-02-05 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_alter_item_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://th.bing.com/th/id/OIP.ISK0kbvLUbQTc9hltD47fAHaF0?pid=ImgDet&rs=1', max_length=500),
        ),
    ]
