# Generated by Django 4.1.4 on 2023-02-10 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_alter_item_item_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item_price',
            new_name='recepie',
        ),
    ]
