# Generated by Django 4.1.4 on 2023-02-13 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_item_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='recepie',
            new_name='recipe',
        ),
    ]
